import type { ProductSummary } from "@/types/product"

export const mockProducts: ProductSummary[] = [
  {
    product_code: "shupatto-41a",
    representative_sku: "shupatto-41a",
    rating: "A",
    product_name: "Shupatto シュパット コンパクトバッグ M/2020 エコバッグ コンビニ レジ袋 MARNA",
    stock_sum: 27,
    sales_units_m: 46,
    access_m: 1085,
    cv_m: 4.06,
    badges: ["高転換率", "人気商品"],
  },
  {
    product_code: "adst-01",
    representative_sku: "ADST-01-V",
    rating: "C",
    product_name: "アドスト プレミアム DS2 FDS2-25 ADST Premium ストレートアイロン",
    stock_sum: 0,
    sales_units_m: 10,
    access_m: 363,
    cv_m: 2.75,
    badges: ["欠品", "要注意"],
  },
  {
    product_code: "emitto-04",
    representative_sku: "EMITTO-04-N1",
    rating: "S",
    product_name: "エスハートエス スカルプブラシ ワールドモデル ショートタイプ ピンクゴールド",
    stock_sum: 86,
    sales_units_m: 25,
    access_m: 259,
    cv_m: 9.65,
    badges: ["高転換率", "優良商品"],
  },
  {
    product_code: "cookin-03a",
    representative_sku: "cookin-03a",
    rating: "A",
    product_name: "パーカーアサヒ クッキンカット HOME S / M / L / LL サイズ豊富 合成ゴム まな板 日本製",
    stock_sum: 21,
    sales_units_m: 15,
    access_m: 252,
    cv_m: 5.95,
    badges: ["高評価"],
  },
  {
    product_code: "bf1854",
    representative_sku: "bf1854",
    rating: "S",
    product_name: "ミクニ ミスティガーデン2nd 交換フィルター 自然気化式 加湿器 抗菌 防カビ",
    stock_sum: 29,
    sales_units_m: 58,
    access_m: 219,
    cv_m: 19.18,
    badges: ["超高転換率", "優良商品", "人気商品"],
  },
  {
    product_code: "decole6",
    representative_sku: "decole6",
    rating: "E",
    product_name: "おでかけポケット ピクニック（りんご）/フォレスト（きのこ）キッズ 子供 ポケット",
    stock_sum: 36,
    sales_units_m: 0,
    access_m: 195,
    cv_m: 0.0,
    badges: ["売上0", "CV低下", "要改善"],
  },
  {
    product_code: "emitto-11",
    representative_sku: "EMITTO-11-R",
    rating: "B",
    product_name: "エスハートエス スカルプブラシ ワールドプレミアム ショート 頭皮マッサージ",
    stock_sum: 0,
    sales_units_m: 17,
    access_m: 171,
    cv_m: 9.94,
    badges: ["欠品", "高転換率"],
  },
  {
    product_code: "papilio10",
    representative_sku: "papilio10",
    rating: "S",
    product_name: "Papilio パピリオ ステイブロウ リフィル 眉墨 アイブロウ ウォータープルーフ",
    stock_sum: 529,
    sales_units_m: 44,
    access_m: 164,
    cv_m: 21.95,
    badges: ["超高転換率", "在庫豊富", "優良商品"],
  },
  {
    product_code: "hand-01",
    representative_sku: "hand-01",
    rating: "D",
    product_name: "プロ 業務用ハンドクリーム 無香料 ゆず のばらの香り 乾燥肌 保湿",
    stock_sum: 5,
    sales_units_m: 3,
    access_m: 147,
    cv_m: 2.04,
    badges: ["低在庫", "CV低下"],
  },
  {
    product_code: "yutaron-01",
    representative_sku: "YUTARON-01-N",
    rating: "E",
    product_name: "湯たロン 8時間持続で繰り返し使える 湯たんぽ 電子レンジ 繰り返し",
    stock_sum: 104,
    sales_units_m: 0,
    access_m: 143,
    cv_m: 0.0,
    badges: ["売上0", "CV低下", "在庫豊富"],
  },
]
